// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbdspqtztkdpmvznzfxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZHNwcXR6dGtkcG12em56ZnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyOTM5MjMsImV4cCI6MjA1MTg2OTkyM30.73JyKeM-KgrxA4_pkOb-0TNK_Lm0wwgQmtKj9P9oXGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);